name: build bastion
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - bastion/**
jobs:
  buildqemu:
    name: "Build ${{ matrix.tag }} with QEMU"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - bastion
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          version: "v0.9.1"
          buildkitd-flags: --debug
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: arm64,arm,386
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            darkyghost/bastion-docker
      - id: commit
        uses: pr-mpt/actions-commit-hash@v2
      - name: Build
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./bastion
          file: ./bastion/Dockerfile
          platforms: linux/amd64,linux/arm64, linux/386, linux/arm/v7, linux/arm/v6
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: darkyghost/bastion_docker:latest,darkyghost/bastion_docker:${{ steps.commit.outputs.short }}
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
